cloud: aviary-prod
region: us-west-2
head_node_type:
  name: head-node-g5
  instance_type: g5.12xlarge
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      head_node: 1
      accelerator_type_a10: 1
worker_node_types: []