from setuptools import find_packages, setup

setup(
    name="aviary",
    version="0.2.1",
    description="A tool to deploy and query LLMs",
    packages=find_packages(include="aviary*"),
    include_package_data=True,
    package_data={"aviary": ["models/*"]},
    entry_points={
        "console_scripts": [
            "aviary=aviary.cli:app",
        ]
    },
    install_requires=[
        "boto3",
        "pydantic",
        "typer>=0.9",
        "rich",
        "typing_extensions~=4.5.0",
        "requests",
        "openai",
    ],
    extras_require={
        # TODO(tchordia): test whether this works, and determine how we can keep requirements
        # in sync
        "backend": [
            "awscrt",
            "async_timeout",
            "torch>=2.0.0",
            "torchaudio>=2.0.0",
            "torchvision>=0.15.2",
            "accelerate",
            "transformers>=4.33.1",
            "datasets",
            "ftfy",
            "tensorboard",
            "sentencepiece",
            "Jinja2",
            "numexpr>=2.7.3",
            "hf_transfer",
            "evaluate",
            "bitsandbytes",
            "vllm",
            "numpy<1.24",
            "ninja",
            "protobuf<3.21.0",
            "torchmetrics",
            "safetensors",
            "pydantic~=1.10.0",
            "einops",
            "markdown-it-py[plugins]",
            "fastapi-versioning",
            "scipy",
            "opentelemetry-api",
            "opentelemetry-sdk",
            "opentelemetry-exporter-otlp",
            "opentelemetry-instrumentation-fastapi",
            "opentelemetry-instrumentation-aiohttp-client",
            "opentelemetry-instrumentation-botocore",
            "opentelemetry-instrumentation-httpx",
            "opentelemetry-instrumentation-redis",
        ],
        "frontend": [
            "gradio",
            "aiorwlock",
            "ray",
            "pymongo",
            "pandas",
            "boto3",
        ],
        "dev": [
            "pre-commit",
            "mypy_extensions",
            "ruff==0.0.270",
            "black==23.3.0",
            "types-PyYAML",
            "types-redis",
            "types-filelock",
            "types-requests",
            "types-cachetools",
        ],
        "test": [
            "pytest",
            "pytest-asyncio",
            "pytest-timeout",
            "buildkite-test-collector",
            "locust",
            "asynctest",
        ],
        "docs": [
            "mkdocs-material",
        ],
    },
    dependency_links=["https://download.pytorch.org/whl/cu118"],
    python_requires=">=3.8",
)
